name: plex

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - VERSION=docker
      # https://www.plex.tv/claim
      - PLEX_CLAIM=<YOUR_TOKEN>
      - PLEX_ACCEPT_EULA=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ./plex:/config
      - /shared:/shared
    # ports:
      # - "32400:32400"
      # - "8324:8324"
      # - "32469:32469"
      # - "1900:1900/udp"
      # - "5353:5353/udp"
      # - "32410:32410/udp"
      # - "32412:32412/udp"
      # - "32413:32413/udp"
      # - "32414:32414/udp"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=32400:32400,8324:8324,32469:32469"
      - "lazy-tcp-proxy.udp-ports=1900:1900,5353:5353,32410:32410,32412:32412,32413:32413"
      # No 'self' discovery (otherwise plex will keep itself alive via port 32414!)
      # - "lazy-tcp-proxy.udp-ports=1900:1900,5353:5353,32410:32410,32412:32412,32413:32413,32414:32414"
      # - "lazy-tcp-proxy.block-list=172.22.0.1" # <- this changes per system
      - "lazy-tcp-proxy.http-healthcheck=http://${container}:32400/"
