name: udp-echo

services:
  # echo "hello" | nc -u localhost 9005
  udp-echo:
    image: alpine
    container_name: udp-echo
    command: ["sh", "-c", "apk add --no-cache socat && socat -v UDP4-RECVFROM:9005,fork EXEC:'cat'"]
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9005:9005"
      - "lazy-tcp-proxy.udp-ports=9005:9005"