name: ollama-gpu

services:
  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_ORIGINS=*
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.http-healthcheck=http://{{container}}:11434/"

  open-webui:
    depends_on:
      ollama:
        condition: service_started
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
    ports:
      - "8080:8080"
    volumes:
      - ./open-webui:/app/backend/data
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9002:8080"
      - "lazy-tcp-proxy.dependants=ollama"
