name: nginx

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    # volumes:
    #   - ./html:/usr/share/nginx/html:ro
    command: >
      sh -c 'echo "events {}\nhttp { server { listen 80; keepalive_timeout 0; location / { root /usr/share/nginx/html; index index.html; } } }" > /etc/nginx/nginx.conf && nginx -g "daemon off;"'
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9006:80"
