name: ollama-gpu

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_ORIGINS=http://192.168.1.1:9001,http://127.0.0.1:9001,http://0.0.0.0:9001
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9001:11434"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
#    ports:
#      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:9001
      - WEBUI_AUTH=false
    volumes:
      - ./open-webui:/app/backend/data
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9002:8080"