name: mariadb

services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-mariadb}
      MARIADB_USER: ${MARIADB_USER:-admin}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=3306:3306"

volumes:
  mariadb:
